// <auto-generated />
namespace eParty.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddSQLInjectionLogEnhancement : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSQLInjectionLogEnhancement));
        
        string IMigrationMetadata.Id
        {
            get { return "202605171906236_AddSQLInjectionLogEnhancement"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
